### ISSUE TITLE
Can I translate game into my language ?

### ISSUE THREAD

**Issue by clovek123** [ivanaedler/MIMPUT#43]
**Can I translate your game into Czech language ?**

**Comment by ivanaedler** [comment]
Hello there! According to http://www.geocities.ws/click2speak/unicode/chars_cs.html, the current Mario font doesnt have support for it, but I can make a way to add these characters. I'll mark this as 'In progress' until I finally found a way out, then I tell you. Thanks!

**Comment by ivanaedler** [comment]
Okay, I uploaded a newer version of the game which supports your language! Just edit 'XMLLanguage_cz' (by downloading it) then make a pull request or just tell me here! Happy fun translating! If any problems, please tell me!

**Comment by clovek123** [comment]
I found a problem text in settings menu does not show š,č,ř,ž,ě,ň,ď,ť as it should.

**Comment by ivanaedler** [comment]
Hello there!
Sorry for the delay to answer.

Hmmm I'll check, it might be due to a missing 'extra unicode' in Tahoma font.



aef23@yandex.com
 
From: clovek123
Date: 2018-02-25 20:53
To: ivanaedler/MIMPUT
CC: Ivan Aedler; State change
Subject: Re: [ivanaedler/MIMPUT] Can I translate game into my language ? (#43)
I found a problem text in settings menu does not show š,č,ř,ž,ě,ň,ď,ť as it should.

**Comment by clovek123** [comment]
I looked on the LoK site where is ver. 3.46 but it still don't work.
PS: It is the OPTIONS menu with tons of options.
