### ISSUE TITLE
EXE link is dead, and a request (or question).

### ISSUE THREAD

**Issue by MarkiThePews** [ivanaedler/MIMPUT#46]
As title, EXE link is dead, and is the EXE still save/load from the flash player %appdata% directory or save/load in it own file, if it's still save/load from the flash player %appdata%, could you possibly make so it save into the file itself or a file in the same directory for portable potential (containing in a usb, playing in multiple machines ?)

**Comment by MarkiThePews** [comment]
Last time I play your game was like 2013-2014 I think, lol

**Comment by ivanaedler** [comment]
EXE link is updated in my github site (official PUT site): https://ivanaedler.github.io/MIMPUT/download.html
The problem of saving in %appdata% is due to Flash mechanism, I cant do anything. BUT! You can save as an external file (Clipboard feature), its the grey clipboard button after pressing SAVE in the PAUSE menu. Then you can load it back in LOAD game screen.
