### ISSUE TITLE
"Same dialogues if the scene is replayed" option is bugged

### ISSUE THREAD

**Issue by jonerjankovic** [ivanaedler/MIMPUT#49]
While playing I noticed that when I had at least 10 lays on one level, peach would talk like a nymph even if it was a new scene. The whole option to turn off nymph messages during scenes isn't working either. I tried cleaning my cache and even setting Peach's personality to innocent but it still wouldn't work. I also know that the option does work in other versions of the game.

**Comment by jonerjankovic** [comment]
OS: windows 7 professional
Browser: Chrome
Flash version: 29.0.0.171

**Comment by ivanaedler** [comment]
I am checking out this bug. Actually, the problem is not with nymph messages, but the random dialogues themselves. The expected logic is to have random dialogues only if she is a nymph (of the level - 10 laids, or for the entire game - 80 laids), AND if she is getting the same fuck pose (that is, its another creature but the scene is the same).

**Comment by ivanaedler** [comment]
Done! I've tested in many situations. Version 3.47. If the bug continues, please reopen it and tell me how to reproduce it.
