### ISSUE TITLE
Errors in closet dialog

### ISSUE THREAD

**Issue by larsrand** [ivanaedler/MIMPUT#7]
There are some errors in the closet dialog that I can't fix because I don't know what you wanted the meaning of the text to be. All I know it's not good english now.

These are the lines:

``` xml
<p i="37">Ahhh! This thing is\ncumming like a shouting mushy!</p>

<p i="50">Yes, fuck\nme! Stuck and let it glued there! Ohhhh!!</p>

<p i="54">I am having\nsex! In my back fanny! Ahhh! It\'s so plucked in!</p>

<p i="55">No, don\'t! Don\'t\npluck in there! Its... my hidden bag... Don\'t fuck it! Oooooh!</p>
```

The probems are:
- `shouting mushy`: What do you mean by this?
- `Stuck and let it glued there`: What do you mean by this?
- `so plucked in`: What do you mean by this?
- `Don\'t\npluck in there`: Should this be "Don't fuck me there", or should it have another meaning?

It would be great if you could take a look at improving these...

As always: thanks for all the great work, on a great game!

**Comment by ivanaedler** [comment]
Thank you for the pinpoints,

**Shouting mushy**: I wanted to say 'a little mushroom that gusts/throws cum on her'
**Stuck and let it glued there**: 'be stuck like a dog's dick. The princess will try to flee but she couldnt because the dick is deeply 'glued' on her for some time.
**So plucked in**: 'so 'glued' deep inside'
**Dont pluck in here** 'dont 'lock it in there'.

The intention of this scene is to show that the princess is 'locked' for some time, until he cums inside her. Thank you, I appreciate the feedback!

**Comment by larsrand** [comment]
I thought the last 3 where also from the toad scene's, so I don't get where the being stuck comes from. But perhaps they are not from toad scene's then...

Anyway, perhaps these are appropriate fixes? 

```
<p i="37">Ahhh! This little shroom\n is showering me with cum!</p>

<p i="50">Yes, fuck\nme! Get stuck inside of me! Ohhhh!!</p>

<p i="54">I am having\nsex! In my back fanny! Ahhh! It\'s dick has lodged itself in me!</p>

<p i="55">No, don\'t! Don\'t\get stuck inside! Its... my hidden bag... Don\'t fuck it! Oooooh!</p>
```

That's better than it originally was, and I hope is has the same meaning as you intended.
This was hard for me to et right, so this might certainly still be improved by someone who is a native english speaker...

**Comment by ivanaedler** [comment]
Great, thats it, thank you! You can proceed!

**Comment by ivanaedler** [comment]
Thank you! I think we can close this issue ;)
